sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 10
  wechat:
    appid: wx278a2a9d474ef82d
    secret: 0a5b8293a5b8d814f0b069e1e34cb820

  alioss:
#    endpoint: oss-cn-beijing.aliyuncs.com
#    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
#    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
#    bucket-name: sky-itcast
#
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t5kbL6yncMQwAQjBDV5`
    access-key-secret: RfEhVYOWoPAuOygMd6Xz2gwYBzFimB
    bucket-name: zyb-sky-itcast
